# Site settings
title: Joshua Alvarado - Portfolio (Dev)
email: joshua.alvarado312@gmail.com
description: Development build of Joshua Alvarado's portfolio site.
baseurl: "" # localhost root
url: ""
github_username: JoshuaAlvarado-hub

# Firebase (development)
firebase:
  apiKey: "AIzaSyArzL_9hbkZ1r_5AXCO2lgJR9EBYGxSNdo"
  authDomain: "joshalvarado-com.firebaseapp.com"
  projectId: "joshalvarado-com"
  storageBucket: "joshalvarado-com.firebasestorage.com"
  messagingSenderId: "539697055519"
  appId: "1:539697055519:web:59bdd478a345eb521bd22a"
  measurementId: "G-DVPCZ6D1RM"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
